# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'GeneralProject' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for GeneralProject
  pod 'R.swift'
  pod 'SwiftLint'
  pod 'RxSwift'
  pod 'RxCocoa'

  target 'GeneralProjectTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'GeneralProjectUITests' do
    # Pods for testing
  end

end
